import { Link } from 'react-router-dom'
import PageTransition from '../components/PageTransition'
import Seo from '../components/Seo'
import { company } from '../data/site'
import { useLocale } from '../i18n'

// Versioned local / optional online beta policy. Publishing does not activate SDKs.
const privacy = {
  en: {
    title: 'Fuflet privacy',
    description: "Privacy information for local play and optional online beta features in Fuflet — The Shapeshifter.",
    draft: "Local play and online beta · updated 7 October 2026",
    scope: "Choose local play without an account, or use available online beta options. Below we explain what each mode processes, your choices and how to request deletion.",
    contents: 'On this page',
    contact: 'Privacy contact',
    companyLink: 'Company details and website terms',
    sections: [
      ['operator', 'Who provides the game', 'Fuflet — The Shapeshifter is provided by Reality Computer Software SRL, Romania. Our contact for privacy questions and requests is realitycomputersoftware.rcs@gmail.com. You can also use realitycomputersoftware@gmail.com.'],
      ["progress", "Playing on this device", "You can play without creating an online game account. Progress, earned currency, items, language and accessibility preferences are stored on your device. Optional online beta features have a separate profile: connecting does not upload or replace your existing local adventure. Available features depend on your installed version; this page does not enable them."],
      ['notes', 'Optional local usage notes', 'Local usage notes are off by default and are not needed to play. If enabled in Settings, they record categories of gameplay actions, numeric values, durations, a day number and error counts. Their record format contains no names, emails, account identifiers, device identifiers, advertising identifiers or raw exception messages. At most 256 recent events are retained, with events older than seven days removed when the game processes the notes. The game does not send this note file to us. Settings lets you turn notes off and delete them.'],
      ['notifications', 'Reminders', 'Reminders for daily tasks and returning to the game are scheduled locally. Android controls notification permission; you can change it in the system settings for Fuflet. Scheduling uses the device clock. This beta does not use a remote push service.'],
      ['backup', 'Storage, backup and deletion', 'Progress and preferences stay in app storage until removed. Clearing the app’s storage also removes local progress. For the complete online beta, starting with version 0.1.180, the game disables Android app-data cloud backup and device transfer so that session credentials and pending reward requests are not copied. Local progress therefore remains on this device; the separate online profile is recovered through its linked account. Earlier offline builds may allow Android backup according to your system settings, excluding local usage notes and performance reports. Uninstalling a newer build does not necessarily delete an existing older system backup; your backup provider controls those copies.'],
      ['support', 'When you contact us', 'If you email us, we receive your address and the information you choose to include. Please do not send passwords, payment details or identity documents. We use correspondence to answer your request and resolve support or privacy issues. The company owner handles requests through a standard Gmail account. Ordinary support messages are deleted 12 months after resolution, unless a documented legal obligation or dispute requires longer retention. This does not override an applicable earlier erasure request. We retain only the minimum record of a privacy request (date, request type and response) for three years after closure, reviewed annually, to document how we handled it. Longer retention requires a documented legal obligation or dispute. Email is processed through Google Gmail, including storage that may be outside the EEA. Google describes the applicable adequacy decisions, EU–US Data Privacy Framework and standard contractual clauses in its transfer information. We use an ordinary Gmail account, not a Google Workspace account.'],
      ["basis", "Purposes and legal grounds", "We use local settings and requested online account/game functions to provide the service you choose (GDPR Article 6(1)(b), where applicable). Limited verification, abuse prevention and ordinary support serve our legitimate interests in keeping the game reliable and protecting players (Article 6(1)(f)); you may object and we assess that request. We use consent where required for optional advertising storage, identifiers and personalisation, with withdrawal through ad privacy settings. Merely viewing the online notice is not blanket consent to advertising. We handle statutory rights requests under Article 6(1)(c). Optional local notes remain off unless you enable them; they are not an online analytics service."],
      ["audience", "Age groups and online access", "Fuflet is intended for teenagers aged 13 and over and adults. In this beta, online accounts, purchases and rewarded ads are available only to players who declare that they are 18 or older. Players under 18, and players who leave the question unanswered, can play locally. We save an age category and the version of the online notice on the device, not a date of birth or a parent’s email. An age declaration is not advertising consent. Changing the age category requires restarting the game so that services already started for an adult are not reused for a younger player."],
      ["account", "Optional online accounts and progress", "If you choose an online option, Unity Authentication processes a game-player identifier and authentication/session information. Choosing Google Play Games also involves Google and a provider identifier used to connect your game account. We do not receive your Google password. Unity Cloud Save and Cloud Code store and process the online profile, balances, owned and equipped items, upgrade levels, supported chapter and clearing progress, contracts, exploration rewards, Journal objectives and seals, and first and latest authenticated activity. Game servers receive run actions, timing, rewards and purchase or ad-verification references to check results, prevent duplicate rewards and recover interrupted requests. Identifiers and hashes linked to your account are personal data, even when they do not contain your name. Internet services also process connection information such as IP addresses and technical request data."],
      ["guest", "Playing online as a guest", "Choosing guest mode creates or reuses an online Unity account without requiring Google sign-in. A session credential stored on this device allows the same account to be reused. This is a pseudonymous account, not data-free local play. Clearing app data, uninstalling or losing the session can make this account inaccessible if it has not been linked to Google Play Games. Linking, where available and successful, keeps the same game account; it does not automatically merge two existing profiles."],
      ["ranking", "What other players see in the Endless ranking", "A verified online Endless result can appear in the shared ranking. Other online players see an automatically generated Fuflet pseudonym, best distance and position. We do not show your Google name, email or internal Unity player identifier. The pseudonym remains associated with the account and is still personal data. Unity Leaderboards processes the internal player identifier, score and connection data to operate the ranking. Scores follow the game-profile retention and deletion rules below. This beta ranking has no seasonal archives; we will explain archive handling before introducing them."],
      ["purchases", "Purchases in the beta", "The current online purchase trial is limited to authorised Google Play licence testers and test transactions. Check that the Google purchase screen explicitly identifies a test before confirming. Real-money sales will require an updated release configuration and retention review. Google Play processes the store transaction. Our server checks its purchase token and product, and keeps account-linked verification references and reward records to prevent granting the same purchase twice. Fuflet does not receive your card or bank details. Unity IAP 5.4 also processes player, installation and session identifiers, device information and country for its commerce service. Unity may use transaction and billing information for its own reporting, legal and security purposes. We have not enabled a webshop or a third-party payment checkout."],
      ["ads", "Optional ads and privacy choices", "Where enabled for adult beta testers, you may choose to watch an ad for a revive or a reward multiplier. Playing locally does not require ads. Google’s User Messaging Platform (UMP) obtains and stores applicable privacy choices before the ad service is started. Age selection and accepting the online information are separate from these choices. You can reopen ad privacy options and pause ads from the game’s settings. Refusing or withdrawing permission can reduce ad availability; it does not automatically grant a revive or bonus. LevelPlay, ironSource and Unity Ads process device or advertising identifiers, IP-derived approximate location, ad views and interactions, technical diagnostics and reward-verification identifiers to deliver and measure ads and prevent fraud. Personalisation and device storage/access subject to consent follow your choices. Google supplies the privacy form; installing UMP does not mean that Fuflet uses Google Analytics or AdMob to serve ads. The signed reward callback passes through our Vercel-hosted endpoint to the game server. We do not publish your internal account identifiers to other players; the ranking uses the public pseudonym described above."],
      ["retention", "How long online information is kept", "Ordinary online beta profiles and their game-linked test-purchase and reward records are scheduled for removal after 24 calendar months without authenticated activity, or earlier following a verified deletion request. This policy is administered by the company; it does not mean that an automatic purge service is already running. A deletion request first stops new game activity, then removes and verifies removal of its ranking score before removing the game data and authentication record. A minimal completion marker may remain for up to seven days to reject late requests; it is then removed through the operator’s cleanup procedure. Unfinished requests are reviewed and resumed, not treated as completed. If a specific legal obligation or dispute requires information to be kept, we limit the retained information and explain the reason and applicable period. Deleting the game account does not delete your Google account, Google Play history or records that providers retain for their own lawful purposes. Unity’s IAP documentation specifies 90 days for IAP service logs and account/order data until deletion is requested; provider-held requests may therefore require separate follow-up."],
      ["providers", "Service providers and international transfers", "Reality Computer Software SRL is responsible for the game data described here. Unity provides authentication, cloud storage, server functions, leaderboards and purchasing technology; Google provides Play Games, Play billing and the UMP privacy service. Unity/ironSource and advertising partners also act under their own privacy notices for relevant advertising or business purposes. Vercel hosts our website and ad-reward endpoint. Gmail handles messages you send to us. These services may process data outside Romania and the European Economic Area. Applicable protections can include adequacy decisions and standard contractual clauses, as described in the providers’ privacy and transfer terms linked below. We do not describe every provider as acting solely on our instructions: advertising, platform accounts and some commerce processing have separate purposes and responsibilities."],
      ["rights", "Access, export and deletion", "Where GDPR applies, you may request access, correction, deletion, restriction and, where applicable, portability; you may object to legitimate-interest processing and withdraw consent without affecting prior lawful processing. Online account settings provide a data export and, in supported beta versions, a deletion flow. You can always submit a request using the web page below or our privacy email, even after uninstalling or losing access to the game. We verify ownership proportionately and do not ask for passwords. A game-server deletion does not itself erase every service provider’s records: we follow up with processors where needed and explain separate provider channels. We normally respond within one month; where a lawful extension is needed, we explain it within that month. You may complain to your local supervisory authority, including Romania’s ANSPDCP."],
      ["future", "Changes and feature availability", "Older offline builds continue to use local play only. Optional online beta features are activated separately after testing; this notice is not an announcement that every feature is already available. We will update the policy and in-game information before introducing materially different processing, real-money sales or additional advertising partners. Website browsing is also covered by the company’s website terms linked below."],
    ],
  },
  ro: {
    title: 'Confidențialitate în Fuflet',
    description: "Date personale în jocul local și funcțiile beta online opționale din Fuflet — The Shapeshifter.",
    draft: "Joc local și beta online · actualizare 7 octombrie 2026",
    scope: "Poți juca local fără cont sau poți folosi opțiunile beta online disponibile. Mai jos explicăm ce date folosește fiecare mod, ce poți alege și cum poți solicita ștergerea.",
    contents: 'Cuprins',
    contact: 'Contact pentru date personale',
    companyLink: 'Datele firmei și termenii site-ului',
    sections: [
      ['operator', 'Cine oferă jocul', 'Fuflet — The Shapeshifter este oferit de Reality Computer Software SRL, România. Pentru întrebări și cereri privind datele personale, ne poți scrie la realitycomputersoftware.rcs@gmail.com. Poți folosi și realitycomputersoftware@gmail.com.'],
      ["progress", "Jocul pe acest dispozitiv", "Poți juca fără să creezi un cont online. Progresul, monedele câștigate, obiectele, limba și preferințele de accesibilitate sunt păstrate pe dispozitiv. Funcțiile online opționale din beta folosesc un profil separat: conectarea nu încarcă și nu înlocuiește aventura locală existentă. Funcțiile disponibile depind de versiunea instalată; această pagină nu le activează."],
      ['notes', 'Înregistrări locale opționale', 'Înregistrările de utilizare sunt dezactivate inițial și nu sunt necesare pentru a juca. Dacă le activezi din Setări, ele păstrează categorii de acțiuni din joc, valori numerice, durate, numărul zilei și numărul erorilor. Formatul lor nu conține nume, adrese de email, identificatori de cont, de dispozitiv sau de publicitate și nici mesajele complete ale erorilor. Sunt păstrate cel mult 256 de evenimente recente; cele mai vechi de șapte zile sunt eliminate când jocul prelucrează înregistrările. Jocul nu ne trimite acest fișier. Din Setări poți dezactiva și șterge înregistrările.'],
      ['notifications', 'Mementouri', 'Mementourile pentru sarcinile zilnice și revenirea în joc sunt programate local. Permisiunea pentru notificări este gestionată de Android și poate fi schimbată în setările telefonului pentru Fuflet. Programarea folosește ceasul dispozitivului. Această versiune nu folosește un serviciu de notificări trimise de la distanță.'],
      ['backup', 'Păstrare, copii de siguranță și ștergere', 'Progresul și preferințele rămân în spațiul aplicației până la ștergere. Ștergerea datelor aplicației elimină și progresul local. Pentru beta cu aventura online completă, începând cu versiunea 0.1.180, jocul dezactivează copierea datelor aplicației în cloud prin Android și transferul lor între dispozitive, pentru a nu copia datele de autentificare și cererile de recompensă în așteptare. Progresul local rămâne pe acest dispozitiv; profilul online separat poate fi recuperat prin contul asociat. Versiunile offline anterioare pot permite copierea prin Android conform setărilor sistemului, excluzând înregistrările locale de utilizare și rapoartele de performanță. Dezinstalarea unei versiuni noi nu șterge neapărat o copie veche deja existentă; acele copii sunt gestionate de furnizorul lor.'],
      ['support', 'Când ne contactezi', 'Dacă ne trimiți un email, primim adresa ta și informațiile pe care alegi să le incluzi. Nu trimite parole, date de plată sau acte de identitate. Folosim corespondența pentru a răspunde și a rezolva cererile de asistență sau privind datele personale. Proprietarul firmei gestionează cererile printr-un cont Gmail obișnuit. Mesajele obișnuite de asistență sunt șterse la 12 luni după rezolvare, cu excepția cazurilor documentate în care o obligație legală sau un litigiu necesită păstrarea lor mai mult timp. Această perioadă nu înlătură dreptul aplicabil de a cere ștergerea mai devreme. Păstrăm numai evidența minimă a unei cereri privind datele personale (data, tipul cererii și răspunsul) timp de trei ani după închidere, cu revizuire anuală, pentru a documenta soluționarea ei. O perioadă mai lungă necesită o obligație legală sau un litigiu documentat. Emailurile sunt prelucrate prin Google Gmail, inclusiv prin stocare care poate fi în afara SEE. Google descrie deciziile de adecvare aplicabile, cadrul UE–SUA pentru protecția datelor și clauzele contractuale standard în informațiile sale despre transferuri. Folosim un cont Gmail obișnuit, nu Google Workspace.'],
      ["basis", "Scopuri și temeiuri de prelucrare", "Folosim setările locale și funcțiile online solicitate pentru a oferi serviciul ales (articolul 6 alineatul (1) litera (b) din GDPR, când se aplică). Verificările limitate, prevenirea abuzurilor și asistența obișnuită susțin interesul nostru legitim de a menține jocul funcțional și a proteja jucătorii (litera (f)); te poți opune și analizăm cererea. Folosim consimțământul unde este necesar pentru stocarea publicitară opțională, identificatori și personalizare; acesta poate fi retras din opțiunile de confidențialitate ale reclamelor. Simpla citire a informării online nu reprezintă acord general pentru reclame. Soluționăm cererile legale privind datele în baza literei (c). Înregistrările locale opționale rămân oprite până le activezi; ele nu reprezintă un serviciu de statistici online."],
      ["audience", "Categorii de vârstă și acces online", "Fuflet se adresează adolescenților de la 13 ani și adulților. În această versiune beta, conturile online, cumpărăturile și reclamele cu recompense sunt disponibile numai celor care declară că au cel puțin 18 ani. Cei sub 18 ani și cei care nu răspund pot juca local. Salvăm pe dispozitiv categoria de vârstă și versiunea informării online, nu data nașterii sau emailul unui părinte. Declararea vârstei nu reprezintă consimțământ pentru reclame. Schimbarea categoriei necesită repornirea jocului, pentru a nu reutiliza pentru un jucător mai tânăr serviciile deja pornite de un adult."],
      ["account", "Conturi și progres online opționale", "Dacă alegi o opțiune online, Unity Authentication prelucrează un identificator de jucător și informații despre autentificare și sesiune. Alegerea Google Play Games implică și Google, precum și un identificator folosit pentru asocierea contului de joc. Nu primim parola contului tău Google. Unity Cloud Save și Cloud Code păstrează și prelucrează profilul online, soldurile, obiectele deținute și echipate, nivelurile îmbunătățirilor, progresul capitolelor și al Poienii în versiunile compatibile, contractele, recompensele de explorare, obiectivele din Jurnal, sigiliile și prima și cea mai recentă activitate autentificată. Serverele primesc acțiuni din cursă, timpi, recompense și referințe pentru verificarea cumpărăturilor sau reclamelor, pentru a valida rezultatele, a evita recompensele duplicate și a recupera cererile întrerupte. Identificatorii și amprentele digitale asociate contului rămân date personale, chiar dacă nu conțin numele tău. Serviciile de internet prelucrează și informații de conexiune, precum adresa IP și date tehnice ale cererilor."],
      ["guest", "Jocul online ca invitat", "Modul de invitat creează sau reutilizează un cont online Unity fără să ceară conectarea la Google. Datele sesiunii salvate pe acest dispozitiv permit revenirea în același cont. Este un cont cu pseudonim, nu joc local fără date online. Ștergerea datelor aplicației, dezinstalarea sau pierderea sesiunii pot face contul inaccesibil dacă nu a fost asociat cu Google Play Games. Asocierea, când este disponibilă și reușește, păstrează același cont de joc; nu unește automat două profiluri existente."],
      ["ranking", "Ce văd ceilalți în clasamentul Fără sfârșit", "Un rezultat validat dintr-o cursă online Fără sfârșit poate apărea în clasamentul comun. Ceilalți jucători online văd un pseudonim Fuflet generat automat, cea mai bună distanță și poziția. Nu afișăm numele Google, emailul sau identificatorul intern Unity. Pseudonimul rămâne asociat contului și este tot o dată personală. Unity Leaderboards prelucrează identificatorul intern, scorul și datele de conexiune pentru funcționarea clasamentului. Scorurile urmează regulile de păstrare și ștergere ale profilului, descrise mai jos. Clasamentul beta nu are arhive sezoniere; vom explica tratarea lor înainte de a le introduce."],
      ["purchases", "Cumpărături în beta", "Testarea actuală a cumpărăturilor online este limitată la testerii autorizați pentru cumpărături de test în Google Play. Înainte de confirmare, verifică dacă ecranul Google precizează explicit că tranzacția este de test. Vânzările cu bani reali vor necesita o configurare de lansare și o revizuire a regulilor de păstrare a datelor. Google Play gestionează tranzacția din magazin. Serverul nostru verifică dovada cumpărării și produsul și păstrează referințe de verificare și recompense asociate contului, pentru a nu acorda aceeași cumpărătură de două ori. Fuflet nu primește datele cardului sau contului bancar. Unity IAP 5.4 prelucrează și identificatori de jucător, instalare și sesiune, informații despre dispozitiv și țară. Unity poate folosi informații despre tranzacții și facturare și pentru raportare proprie, obligații legale și securitate. Nu am activat un magazin web sau plata printr-un alt furnizor."],
      ["ads", "Reclame opționale și alegeri de confidențialitate", "Când funcția este activată pentru testerii adulți, poți alege să vezi o reclamă pentru o reînviere sau multiplicarea unei recompense. Jocul local nu necesită reclame. Platforma Google UMP prezintă și păstrează opțiunile aplicabile de confidențialitate înainte de pornirea serviciului de reclame. Alegerea vârstei și confirmarea informării online sunt separate de aceste opțiuni. Din setările jocului poți redeschide opțiunile de confidențialitate pentru reclame și poți opri reclamele. Refuzul sau retragerea permisiunii poate reduce disponibilitatea reclamelor; nu acordă automat o reînviere sau un bonus. LevelPlay, ironSource și Unity Ads prelucrează identificatori de dispozitiv sau publicitate, localizarea aproximativă dedusă din IP, vizualizări și interacțiuni cu reclamele, date tehnice și identificatori pentru verificarea recompenselor. Scopurile sunt afișarea și măsurarea reclamelor și prevenirea fraudei. Personalizarea și accesul la datele dispozitivului care necesită consimțământ respectă alegerile tale. Google furnizează formularul; instalarea UMP nu înseamnă că jocul folosește Google Analytics sau AdMob pentru afișarea reclamelor. Confirmarea semnată a recompensei trece prin serviciul nostru găzduit de Vercel către serverul jocului. Nu publicăm identificatorii interni ai contului pentru ceilalți jucători; clasamentul folosește pseudonimul public descris mai sus."],
      ["retention", "Cât păstrăm informațiile online", "Profilurile obișnuite din beta online, împreună cu înregistrările de recompense și cumpărături de test asociate, sunt prevăzute pentru ștergere după 24 de luni calendaristice fără activitate autentificată sau mai devreme, la cerere verificată. Firma aplică această regulă; ea nu înseamnă că rulează deja un serviciu automat de ștergere. O cerere de ștergere oprește întâi activitatea nouă din cont, apoi elimină scorul din clasament și verifică ștergerea lui înainte de eliminarea datelor de joc și a înregistrării de autentificare. O evidență tehnică minimă a finalizării poate rămâne până la șapte zile, pentru a respinge cererile întârziate; apoi este eliminată prin procedura operatorului. Cererile neterminate sunt verificate și reluate, nu considerate finalizate. Dacă o obligație legală sau un litigiu impune păstrarea unor informații, limităm datele reținute și explicăm motivul și perioada aplicabilă. Ștergerea contului de joc nu șterge contul Google, istoricul Google Play sau evidențele păstrate de furnizori pentru propriile scopuri legale. Documentația Unity IAP indică 90 de zile pentru jurnalele tehnice IAP și păstrarea datelor de cont și comandă până la solicitarea ștergerii; cererile către furnizori pot necesita urmărire separată."],
      ["providers", "Furnizori și transferuri internaționale", "Reality Computer Software SRL răspunde pentru datele jocului descrise aici. Unity furnizează autentificarea, stocarea pe server, funcțiile de server, clasamentele și tehnologia de cumpărare; Google furnizează Play Games, plățile Play și serviciul de confidențialitate UMP. Unity/ironSource și partenerii publicitari acționează și potrivit propriilor politici, pentru scopurile publicitare sau comerciale relevante. Vercel găzduiește site-ul și punctul de primire a confirmărilor de recompense publicitare. Gmail gestionează mesajele trimise de tine. Aceste servicii pot prelucra date în afara României și a Spațiului Economic European. Protecțiile aplicabile pot include decizii de adecvare și clauze contractuale standard, descrise în politicile și condițiile de transfer ale furnizorilor de mai jos. Nu prezentăm toți furnizorii ca acționând exclusiv după instrucțiunile noastre: publicitatea, conturile platformelor și unele prelucrări comerciale au scopuri și responsabilități distincte."],
      ["rights", "Acces, export și ștergere", "Când se aplică GDPR, poți cere acces, corectare, ștergere, restricționare și, după caz, portabilitate. Te poți opune prelucrării bazate pe interes legitim și îți poți retrage consimțământul fără a afecta prelucrările anterioare legale. Setările contului online oferă exportul datelor și, în versiunile beta compatibile, un flux de ștergere. Poți oricând trimite o cerere prin pagina de mai jos sau la emailul nostru, inclusiv după dezinstalare ori pierderea accesului la joc. Verificăm proporțional dreptul asupra contului și nu cerem parole. Ștergerea de pe serverul jocului nu elimină automat toate evidențele furnizorilor: urmărim separat cererile către cei care prelucrează date pentru noi și explicăm canalele proprii ale furnizorilor. De regulă răspundem într-o lună; dacă este necesară o prelungire permisă de lege, o explicăm în acest termen. Poți reclama la autoritatea competentă, inclusiv ANSPDCP în România."],
      ["future", "Schimbări și disponibilitatea funcțiilor", "Versiunile offline mai vechi continuă să funcționeze local. Funcțiile beta online opționale sunt activate separat după testare; această informare nu anunță că toate sunt deja disponibile. Vom actualiza politica și informarea din joc înainte de prelucrări semnificativ diferite, vânzări cu bani reali sau parteneri publicitari suplimentari. Navigarea pe site este acoperită și de condițiile firmei de mai jos."],
    ],
  },
}

export default function FufletPrivacyPage() {
  const { locale } = useLocale()
  const copy = privacy[locale]
  return (
    <PageTransition>
      <Seo title={`${copy.title} | Reality Computer Software`} description={copy.description} path="/fuflet/privacy" />
      <article className="section" style={{ maxWidth: 860, marginInline: 'auto', paddingTop: 'clamp(7rem, 12vw, 10rem)', paddingBottom: '5rem' }}>
        <p className="eyebrow">Fuflet — The Shapeshifter</p>
        <h1 style={{ fontSize: 'clamp(2rem, 5vw, 3.6rem)', overflowWrap: 'anywhere' }}>{copy.title}</h1>
        <p role="note" className="tag" style={{ display: 'block', whiteSpace: 'normal', marginBlock: '1.5rem' }}>{copy.draft}</p>
        <p className="lede">{copy.scope}</p>
        <nav aria-label={copy.contents} style={{ marginBlock: '2rem' }}>
          <h2 style={{ fontSize: '1.1rem' }}>{copy.contents}</h2>
          <ol style={{ paddingLeft: '1.4rem', lineHeight: 2 }}>
            {copy.sections.map(([id, title]) => <li key={id}><a href={`#${id}`}>{title}</a></li>)}
          </ol>
        </nav>
        {copy.sections.map(([id, title, body]) => (
          <section key={id} id={id} style={{ scrollMarginTop: '7rem', paddingBlock: '1.25rem', borderTop: '1px solid rgba(128,128,128,.25)' }}>
            <h2 style={{ fontSize: '1.5rem', marginBottom: '.75rem' }}>{title}</h2>
            <p style={{ lineHeight: 1.8, overflowWrap: 'anywhere' }}>{body}</p>
            {id === 'operator' && <p style={{ lineHeight: 1.8 }}>{company.registeredOffice} · CUI {company.cui} · {company.tradeRegister}</p>}
            {id === 'support' && <p style={{ lineHeight: 1.8 }}><a href="https://policies.google.com/privacy">Google Privacy</a> · <a href="https://policies.google.com/privacy/frameworks">Google — data transfers</a></p>}
            {id === 'providers' && <p style={{ lineHeight: 2 }}><a href="https://unity.com/legal/privacy-policy">Unity Privacy</a> · <a href="https://unity.com/legal/unity-data-processing-addendum-dpa">Unity DPA</a> · <a href="https://policies.google.com/privacy">Google Privacy</a> · <a href="https://policies.google.com/privacy/frameworks">Google — transfers</a> · <a href="https://www.is.com/privacy-policy/">ironSource Privacy</a> · <a href="https://vercel.com/legal/privacy-policy">Vercel Privacy</a> · <a href="https://vercel.com/legal/dpa">Vercel DPA</a></p>}
            {id === 'retention' && <p style={{ lineHeight: 1.8 }}><a href="https://docs.unity.com/en-us/iap/privacy-and-consent/overview">Unity IAP — privacy, retention &amp; requests</a></p>}
            {id === 'rights' && <><p style={{ marginBlock: '1rem' }}><Link to="/fuflet/delete-account">{locale === 'ro' ? 'Solicită ștergerea contului sau a datelor Fuflet' : 'Request deletion of your Fuflet account or data'}</Link></p><a href="https://www.dataprotection.ro/">ANSPDCP</a></>}
          </section>
        ))}
        <p style={{ marginBlock: '1.5rem', overflowWrap: 'anywhere' }}>{copy.contact}: <a href="mailto:realitycomputersoftware.rcs@gmail.com">realitycomputersoftware.rcs@gmail.com</a></p>
        <Link to="/legal">{copy.companyLink}</Link>
      </article>
    </PageTransition>
  )
}
